name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv for package management
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        uv pip install --system pylint 
        uv pip install --system -r pyproject.toml
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --rcfile pylintrc
